# Generated by Django 4.0.6 on 2023-04-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='dateIdentified',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data da identificação'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='eventDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='georeferenceDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data do georeferenciamento'),
        ),
    ]
